FROM ubuntu:14.04

MAINTAINER Alireza Mehrtash <mehrtash@bwh.harvard.edu>

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget && \
    mkdir -p $CONDA_DIR && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -f -b -p $CONDA_DIR && \
    rm ~/anaconda.sh

RUN pip install --upgrade pip && \
    pip install SimpleITK && \
    pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp36-cp36m-linux_x86_64.whl && \
    pip install keras

ADD . /source
ENTRYPOINT ["python", "source/infer.py"]

